import './style.css'
import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import JSZip from 'jszip'
const $=s=>document.querySelector(s), LOCAL='geofoto_offline_v2', CFG='geofoto_cfg_v1'
let token=sessionStorage.getItem('gf_token')||'',role=sessionStorage.getItem('gf_role')||'user',points=[],map,markers,stream=null,raw='',photo='',geo=null,cfg=loadCfg(),saving=false,savedPhotoKey=''
const TEMPLATES={
essential:{name:'Essencial',description:'Dados principais com mapa e identificação.',top:true,panel:.27,map:true,mapWidth:.34,mapHeight:.23,titleScale:.034,textScale:.019},
compact:{name:'Compacto',description:'Faixa menor, com mini mapa e mais espaço para a imagem.',top:true,panel:.12,map:true,textScale:.013},
location:{name:'Localização',description:'Prioriza coordenadas, endereço e mapa maior.',top:true,panel:.30,map:true,mapWidth:.38,mapHeight:.25,titleScale:.034,textScale:.0185},
corporate:{name:'Corporativo',description:'Visual limpo com identidade da organização e mini mapa.',top:true,panel:.16,map:true,light:true},
technical:{name:'Técnico',description:'Coordenadas, precisão, cidade, endereço e observação.',top:false,panel:.28,map:true,mapWidth:.34,mapHeight:.23,titleScale:.032,textScale:.0185},
evidence:{name:'Evidência',description:'Registro objetivo para comprovação de serviço com mini mapa.',top:true,panel:.14,map:true,note:true},
minimal:{name:'Minimalista',description:'Identificação, data, coordenadas e mini mapa.',top:false,panel:.10,map:true,minimal:true,note:false}
}
function templateRows(t){if(t.minimal)return[`Data/Hora: ${fmt(new Date())}`,`GPS: ${geo?.latitude?.toFixed(6)||'-'}, ${geo?.longitude?.toFixed(6)||'-'}`];const rows=[`Data/Hora: ${fmt(new Date())}`,`Latitude: ${geo?.latitude?.toFixed(6)||'-'}  Longitude: ${geo?.longitude?.toFixed(6)||'-'}`,`Precisão: ${Math.round(geo?.accuracy||0)} m`,`Cidade: ${geo?.city||'Não identificada'}`,`Endereço: ${(geo?.address||'Não identificado').slice(0,80)}`];return rows}
L.Icon.Default.mergeOptions({iconRetinaUrl:'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon-2x.png',iconUrl:'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon.png',shadowUrl:'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-shadow.png'})
function loadCfg(){const d={appName:'GEOFOTO KMZ',company:'',banner:'',primaryColor:'#0f766e',defaultTemplate:'essential',enabledTemplates:['essential','compact','location','corporate','technical','evidence','minimal'],showLogo:true,showMap:true};try{return {...d,...JSON.parse(localStorage.getItem(CFG)||'{}')}}catch{return d}}
function saveCfg(){localStorage.setItem(CFG,JSON.stringify(cfg))}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch('/api'+path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Falha na comunicação');return d}
async function apiBlob(path){const h={};if(token)h.Authorization=`Bearer ${token}`;const url=path.startsWith('/api/')?path:'/api'+path;const r=await fetch(url,{headers:h});if(!r.ok)throw Error('Falha ao carregar foto');return r.blob()}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function loginView(){stopCamera();$('#app').innerHTML=`<main class="login"><div class="login-card"><div class="brand"><div class="logo">⌖</div><div><h1>GEOFOTO KMZ</h1><div class="muted">Registro georreferenciado de campo</div></div></div><form id="loginForm"><label class="field">Usuário<input id="user" autocomplete="username" required></label><label class="field">Senha<input id="pass" type="password" autocomplete="current-password" required></label><button class="btn primary full">Entrar</button><p id="loginMsg" class="muted"></p></form></div></main>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/login',{method:'POST',body:JSON.stringify({user:$('#user').value,pass:$('#pass').value})});token=d.token;role=d.role||'user';sessionStorage.setItem('gf_token',token);sessionStorage.setItem('gf_role',role);await appView()}catch(x){$('#loginMsg').textContent=x.message}}}
async function appView(){$('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="logo">⌖</div><b>GEOFOTO KMZ</b></div><nav class="nav"><button data-page="dashboard">▦ Painel</button><button class="active" data-page="capture">◎ Câmera</button><button data-page="mapa">⌖ Mapa</button><button data-page="records">☷ Registros</button><button data-page="export">⇩ Exportar</button><button data-page="settings">⚙ Configurações</button></nav></aside><main class="main"><header class="top"><div><h2 id="title">Câmera</h2><span class="muted">Tirou a foto = salvou o ponto automaticamente</span></div><span id="netStatus" class="status">● Conectando</span></header><section id="dashboard" class="section"></section><section id="capture" class="section active"></section><section id="mapa" class="section"><div class="card"><div id="map"></div></div></section><section id="records" class="section"></section><section id="export" class="section"></section><section id="settings" class="section"></section></main></div>`;document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>show(b.dataset.page,b));await syncDown();renderAll();setTimeout(startCameraAndGps,120)}
function show(id,b){if(id!=='capture')stopCamera();document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').textContent={dashboard:'Painel',capture:'Câmera',mapa:'Mapa geral',records:'Registros',export:'Exportar KML/KMZ',settings:'Configurações'}[id];if(id==='capture')setTimeout(startCameraAndGps,80);if(id==='mapa')setTimeout(()=>{initMap();map.invalidateSize()},180)}
async function syncDown(){try{points=await api('/points');try{cfg={...cfg,...await api('/config')};saveCfg()}catch{};$('#netStatus')&&($('#netStatus').textContent='● Nuvem conectada')}catch{points=JSON.parse(localStorage.getItem(LOCAL)||'[]');$('#netStatus')&&($('#netStatus').textContent='● Modo offline')}}
function renderAll(){renderDashboard();renderCapture();renderRecords();renderExport();renderSettings()}
function renderDashboard(){const hoje=new Date().toLocaleDateString('pt-BR'),n=points.filter(p=>new Date(p.time).toLocaleDateString('pt-BR')===hoje).length;$('#dashboard').innerHTML=`<div class="cards"><div class="card"><span class="muted">Total de pontos</span><div class="metric">${points.length}</div></div><div class="card"><span class="muted">Fotos hoje</span><div class="metric">${n}</div></div><div class="card"><span class="muted">Com endereço</span><div class="metric">${points.filter(p=>p.address).length}</div></div><div class="card"><span class="muted">KMZ central</span><div class="metric">OK</div></div></div><div class="grid2"><div class="card"><h3>Fluxo automático</h3><p class="muted">A câmera abre, o GPS é obtido e, ao tirar a foto, o ponto é salvo automaticamente no mapa e no KMZ.</p><button class="btn primary" id="quick">Abrir câmera</button></div><div class="card"><h3>Últimos registros</h3>${points.slice(-4).reverse().map(p=>`<p><b>${esc(p.name)}</b><br><span class="muted">${fmt(p.time)} · ${esc(p.city||'')}</span></p>`).join('')||'<p class="muted">Nenhum registro.</p>'}</div></div>`;$('#quick').onclick=()=>document.querySelector('[data-page="capture"]').click()}
function renderCapture(){raw='';photo='';geo=null;saving=false;savedPhotoKey='';const enabled=(cfg.enabledTemplates||Object.keys(TEMPLATES)).filter(id=>TEMPLATES[id]);const current=enabled.includes(cfg.defaultTemplate)?cfg.defaultTemplate:(enabled[0]||'essential');$('#capture').innerHTML=`<div class="grid2 mobile-main"><div class="card capture"><h3>Câmera de campo</h3><label class="field">Modelo da foto<select id="templateSelect">${enabled.map(id=>`<option value="${id}" ${id===current?'selected':''}>${TEMPLATES[id].name}</option>`).join('')}</select></label><div id="templateHint" class="muted small">${TEMPLATES[current]?.description||''}</div><label class="field"><b>Identificação do ponto *</b><input id="pointName" placeholder="Ex.: CEO 80551 / POSTE 023" autocomplete="off" autocapitalize="characters" spellcheck="false" required></label><div id="pointNameHint" class="muted small">Informe a identificação para liberar a câmera.</div><video id="camera" class="camera-large" autoplay playsinline muted></video><canvas id="canvas" class="hidden"></canvas><img id="preview" class="camera-large hidden"><div class="actions"><button class="btn primary" id="take">📷 Tirar foto</button><button class="btn secondary hidden" id="retake">↻ Tirar novamente</button></div><label class="field">Observação<textarea id="note" rows="3" placeholder="Descrição opcional"></textarea></label><div class="actions"><button class="btn secondary" id="gps">Atualizar GPS</button></div><div class="actions hidden" id="shareActions"><button class="btn primary" id="shareBtn">📤 Enviar</button><button class="btn secondary" id="downloadBtn">⬇ Salvar foto</button></div><div id="saveStatus" class="statusline">Aguardando foto...</div><div id="camInfo" class="muted">Abrindo câmera...</div><div id="gpsInfo" class="muted">Obtendo GPS...</div></div><div class="card"><h3>Modelo ativo</h3><div id="templatePreview" class="template-preview"><b>${TEMPLATES[current]?.name||'Essencial'}</b><p class="muted">${TEMPLATES[current]?.description||''}</p></div><p class="muted">A identidade da empresa é opcional. O GeoFoto KMZ funciona com qualquer organização ou sem marca.</p></div></div>`;const pn=$('#pointName'),hint=$('#pointNameHint');pn.addEventListener('input',()=>{const start=pn.selectionStart,end=pn.selectionEnd;pn.value=pn.value.toLocaleUpperCase('pt-BR');try{pn.setSelectionRange(start,end)}catch{}hint.textContent=pn.value.trim()?'Identificação informada.':'Você também pode informar ao tocar em Tirar foto.'});$('#take').onclick=takePhoto;$('#retake').onclick=retake;$('#gps').onclick=getGps;$('#templateSelect').onchange=e=>{const t=TEMPLATES[e.target.value];$('#templateHint').textContent=t?.description||'';$('#templatePreview').innerHTML=`<b>${t?.name||''}</b><p class="muted">${t?.description||''}</p>`}}
async function startCameraAndGps(){await startCamera();getGps()}
async function startCamera(){const v=$('#camera');if(!v)return;try{stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=stream;await v.play();$('#camInfo').textContent='Câmera pronta.'}catch(e){$('#camInfo').textContent='Não foi possível abrir a câmera: '+e.message}}
async function takePhoto(){const pn=$('#pointName');let pointName=(pn?.value.trim()||'').toLocaleUpperCase('pt-BR');if(!pointName){pointName=(window.prompt('Identificação do ponto\nEx.: CEO 80551 / POSTE 023','')||'').trim().toLocaleUpperCase('pt-BR');if(!pointName){const hint=$('#pointNameHint');if(hint)hint.textContent='⚠ É necessário informar a identificação antes da foto.';return}if(pn)pn.value=pointName;const hint=$('#pointNameHint');if(hint)hint.textContent='Identificação informada.'}const v=$('#camera'),c=$('#canvas');if(!v||!v.videoWidth)return;const portrait=innerHeight>innerWidth;const outW=portrait?1080:1920,outH=portrait?1440:1080;c.width=outW;c.height=outH;const sx=v.videoWidth,sy=v.videoHeight,src= sx/sy, dst=outW/outH;let sw=sx,sh=sy,ox=0,oy=0;if(src>dst){sw=Math.round(sy*dst);ox=Math.round((sx-sw)/2)}else{sh=Math.round(sx/dst);oy=Math.round((sy-sh)/2)}c.getContext('2d').drawImage(v,ox,oy,sw,sh,0,0,outW,outH);raw=c.toDataURL('image/jpeg',.9);savedPhotoKey=raw.slice(0,80)+Date.now();stopCamera();$('#saveStatus').textContent='Foto tirada. Preparando dados e salvamento automático...';await annotate();captureUi();await maybeAutoSave()}
async function annotate(){
 if(!raw)return;
 const img=await loadImg(raw),c=document.createElement('canvas'),x=c.getContext('2d'),id=$('#templateSelect')?.value||cfg.defaultTemplate||'essential',t=TEMPLATES[id]||TEMPLATES.essential;
 c.width=img.width;c.height=img.height;x.drawImage(img,0,0);
 const pad=Math.round(c.width*.028),hasMap=t.map&&cfg.showMap!==false,panelRatio=Math.max(.12,Math.min(.34,Number(t.panel||(hasMap?.27:.22)))),panelH=Math.round(c.height*panelRatio),panelY=c.height-panelH-Math.round(pad*.55),cardX=pad,cardW=c.width-pad*2,r=Math.round(pad*.75);
 if(t.top&&cfg.showLogo!==false){
   const headerName=(cfg.appName||'GEOFOTO KMZ').trim().toLocaleUpperCase('pt-BR'),pillW=Math.round(c.width*.31),pillH=Math.round(c.height*.062);
   x.fillStyle='rgba(7,18,31,.78)';if(x.roundRect){x.beginPath();x.roundRect(pad,pad,pillW,pillH,r*.55);x.fill()}else x.fillRect(pad,pad,pillW,pillH);
   x.fillStyle='#fff';x.font='800 '+Math.max(24,Math.round(c.width*.028))+'px Arial';x.fillText(headerName,pad+Math.round(pad*.55),pad+Math.round(pillH*.66),pillW-pad);
   if(cfg.banner){try{const bi=await loadImg(cfg.banner),boxW=Math.round(c.width*.24),boxH=Math.round(c.height*.105),bx=c.width-pad-boxW,by=pad,ratio=Math.min((boxW-pad)/bi.width,(boxH-pad*.6)/bi.height),dw=bi.width*ratio,dh=bi.height*ratio;
    x.fillStyle='rgba(255,255,255,.86)';if(x.roundRect){x.beginPath();x.roundRect(bx,by,boxW,boxH,r*.55);x.fill()}else x.fillRect(bx,by,boxW,boxH);
    x.drawImage(bi,bx+(boxW-dw)/2,by+(boxH-dh)/2,dw,dh)}catch{}}
 }
 x.save();x.fillStyle=t.light?'rgba(255,255,255,.94)':'rgba(7,18,31,.78)';
 if(x.roundRect){x.beginPath();x.roundRect(cardX,panelY,cardW,panelH,r);x.fill()}else x.fillRect(cardX,panelY,cardW,panelH);
 x.restore();
 const fg=t.light?'#102235':'#fff',muted=t.light?'#4d6070':'#d9e3ec',title=($('#pointName')?.value.trim()||('Ponto '+(points.length+1))).toLocaleUpperCase('pt-BR'),displayName=(cfg.company||'').trim(),titleScale=Number(t.titleScale||.034),textScale=Number(t.textScale||.019);
 const textX=cardX+pad,textW=hasMap?Math.round(cardW*.52):cardW-pad*2;
 const now=new Date(),timeText=now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),dateText=now.toLocaleDateString('pt-BR');
 const lat=geo?.latitude?.toFixed(6)||'-',lng=geo?.longitude?.toFixed(6)||'-',acc=Math.round(geo?.accuracy||0),city=geo?.city||'Nao identificada',address=(geo?.address||'Nao identificado').replace(/,\s*Regi[aã]o\s+Sul,?/i,'').replace(/,\s*Brasil$/i,'').replace(/,\s*$/,'').slice(0,92);
 x.fillStyle=fg;x.font='800 '+Math.max(30,Math.round(c.width*titleScale))+'px Arial';x.fillText(title,textX,panelY+Math.round(panelH*.12),textW);if(displayName){x.fillStyle=muted;x.font='700 '+Math.max(20,Math.round(c.width*textScale))+'px Arial';x.fillText('Nome: '+displayName,textX,panelY+Math.round(panelH*.23),textW);}
 x.fillStyle=fg;x.font='850 '+Math.max(44,Math.round(c.width*Math.max(.044,textScale*2.2)))+'px Arial';x.fillText(timeText,textX,panelY+Math.round(panelH*.40),textW);
 x.fillStyle=muted;x.font='700 '+Math.max(21,Math.round(c.width*textScale))+'px Arial';x.fillText(dateText,textX,panelY+Math.round(panelH*.51),textW);
 x.font='650 '+Math.max(19,Math.round(c.width*Math.max(.0175,textScale*.94)))+'px Arial';
 let yy=panelY+Math.round(panelH*.62),line=Math.round(panelH*.095);
 yy=drawWrappedText(x,'GPS: '+lat+', '+lng,textX,yy,textW,line,1);
 yy=drawWrappedText(x,'Precisao: '+acc+' m  •  '+city,textX,yy,textW,line,1);
 yy=drawWrappedText(x,'Endereco: '+address,textX,yy,textW,line,2);
 const note=$('#note')?.value.trim();if(note&&t.note!==false){x.fillStyle=fg;yy=drawWrappedText(x,'Obs.: '+note.slice(0,60),textX,yy,textW,line,1)}
 const footerY=panelY+panelH-Math.round(pad*.82);x.fillStyle='#22c55e';x.beginPath();x.arc(textX,footerY,Math.max(7,Math.round(c.width*.006)),0,Math.PI*2);x.fill();
 x.fillStyle=muted;x.font='600 '+Math.max(14,Math.round(c.width*.013))+'px Arial';x.fillText('GPS OK • Foto registrada',textX+Math.round(pad*.5),footerY+Math.round(pad*.16),textW);
 if(hasMap){
   const mw=Math.round(cardW*(Number(t.mapWidth)||.34)),mh=Math.min(Math.round(c.height*(Number(t.mapHeight)||.20)),Math.round(panelH*.70)),mx=cardX+cardW-pad-mw,my=panelY+Math.round((panelH-mh)/2);
   await miniMap(x,mx,my,mw,mh);
 }
 photo=c.toDataURL('image/jpeg',.92)
}
function drawWrappedText(x,text,a,b,maxW,lineH,maxLines=2){const words=String(text).split(' ');let line='',lines=0;for(const w of words){const test=line?line+' '+w:w;if(x.measureText(test).width>maxW&&line){x.fillText(line,a,b);b+=lineH;lines++;line=w;if(lines>=maxLines-1)break}else line=test}if(line&&lines<maxLines){x.fillText(line,a,b);b+=lineH}return b}
function topBar(x,w,h){x.fillStyle=cfg.primaryColor||'#0f766e';x.fillRect(0,0,w,h);x.fillStyle='#fff';x.font=`bold ${Math.max(24,Math.round(w*.028))}px Arial`;x.fillText(cfg.company||cfg.appName||'GeoFoto KMZ',Math.round(w*.03),Math.round(h*.62))}
async function miniMap(x,a,b,w,h){
 if(geo){
   try{
     const img=await loadOsmSnapshot(geo.latitude,geo.longitude,Math.max(420,Math.round(w*1.08)),Math.max(300,Math.round(h*1.08)),17);
     x.save();
     if(x.roundRect){x.beginPath();x.roundRect(a,b,w,h,Math.round(w*.035));x.clip()}
     x.drawImage(img,a,b,w,h);
     const cx=a+w/2,cy=b+h/2;
     x.fillStyle='rgba(37,99,235,.22)';x.beginPath();x.arc(cx,cy,Math.max(24,w*.07),0,Math.PI*2);x.fill();
     x.fillStyle='#2563eb';x.beginPath();x.arc(cx,cy,Math.max(10,w*.026),0,Math.PI*2);x.fill();
     x.strokeStyle='#fff';x.lineWidth=Math.max(3,w*.006);x.stroke();
     x.restore();
     x.strokeStyle='rgba(255,255,255,.95)';x.lineWidth=Math.max(2,w*.004);
     if(x.roundRect){x.beginPath();x.roundRect(a,b,w,h,Math.round(w*.035));x.stroke()}else x.strokeRect(a,b,w,h);
     return
   }catch{}
 }
 x.fillStyle='rgba(255,255,255,.10)';x.fillRect(a,b,w,h);x.strokeStyle='rgba(255,255,255,.8)';x.strokeRect(a,b,w,h);
 x.fillStyle='#fff';x.font='700 '+Math.max(18,w*.05)+'px Arial';x.fillText('MAPA / GPS',a+16,b+30);
}
async function loadOsmSnapshot(lat,lng,w=700,h=420,z=18){
 const src='/api/static-map?lat='+encodeURIComponent(lat)+'&lng='+encodeURIComponent(lng)+'&w='+Math.round(w)+'&h='+Math.round(h)+'&z='+Math.round(z);
 try{return await loadImg(src)}
 catch{
  const c=document.createElement('canvas'),g=c.getContext('2d');c.width=w;c.height=h;
  g.fillStyle='#dfe7ee';g.fillRect(0,0,w,h);g.strokeStyle='#b7c7d5';g.lineWidth=Math.max(2,w*.004);
  for(let i=-h;i<w+h;i+=Math.max(55,w*.12)){g.beginPath();g.moveTo(i,0);g.lineTo(i+h,h);g.stroke()}
  g.fillStyle='#2563eb';g.beginPath();g.arc(w/2,h/2,Math.max(10,w*.025),0,Math.PI*2);g.fill();
  g.strokeStyle='#fff';g.lineWidth=Math.max(3,w*.006);g.stroke();return c
 }
}
function loadImg(src){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=src})}
function captureUi(){const v=$('#camera'),p=$('#preview');p.src=photo||raw;p.classList.remove('hidden');v.classList.add('hidden');$('#take').classList.add('hidden');$('#retake').classList.remove('hidden');$('#shareActions').classList.remove('hidden');$('#shareBtn').onclick=shareCurrent;$('#downloadBtn').onclick=downloadCurrentPhoto}
function retake(){raw='';photo='';savedPhotoKey='';saving=false;$('#preview').classList.add('hidden');$('#camera').classList.remove('hidden');$('#take').classList.remove('hidden');$('#retake').classList.add('hidden');$('#shareActions').classList.add('hidden');$('#saveStatus').textContent='Aguardando nova foto...';startCamera();getGps()}
async function getGps(){const el=$('#gpsInfo');if(!el)return;if(!navigator.geolocation){el.textContent='GPS indisponível.';return}el.textContent='Obtendo GPS de alta precisão...';navigator.geolocation.getCurrentPosition(async p=>{geo={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};const r=await reverse(geo.latitude,geo.longitude);geo.city=r.city;geo.address=r.address;el.innerHTML=`Latitude: <b>${geo.latitude.toFixed(6)}</b> · Longitude: <b>${geo.longitude.toFixed(6)}</b> · Precisão: <b>${Math.round(geo.accuracy)} m</b><br><b>${esc(geo.city)}</b> · ${esc(geo.address)}`;if(raw){await annotate();captureUi();await maybeAutoSave()}},e=>el.textContent='Falha no GPS: '+e.message,{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function reverse(lat,lng){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}`),d=await r.json(),a=d.address||{};return{address:d.display_name||'',city:a.city||a.town||a.village||a.municipality||a.county||''}}catch{return{address:'',city:''}}}
async function maybeAutoSave(){if(!photo||!geo||saving||!savedPhotoKey)return;const key=savedPhotoKey;saving=true;const st=$('#saveStatus');if(st)st.textContent='Salvando automaticamente e adicionando o pino ao mapa/KMZ...';const p={id:crypto.randomUUID(),name:($('#pointName').value.trim()||`Ponto ${points.length+1}`).toLocaleUpperCase('pt-BR'),note:$('#note').value.trim(),lat:geo.latitude,lng:geo.longitude,accuracy:geo.accuracy,time:new Date().toISOString(),city:geo.city||'',address:geo.address||'',photo};try{await api('/points',{method:'POST',body:JSON.stringify(p)});await syncDown();if(st)st.textContent='✓ Salvo automaticamente. Pino adicionado ao mapa e ao KMZ.';renderDashboard();renderRecords();renderExport();if(map){initMap();setTimeout(()=>map.invalidateSize(),50)}}catch{points.push(p);localStorage.setItem(LOCAL,JSON.stringify(points));if(st)st.textContent='✓ Salvo neste aparelho. Será necessário sincronizar quando houver internet.'}finally{if(savedPhotoKey===key)saving=false}}
async function downloadCurrentPhoto(){const src=photo||raw;if(!src)return;const blob=dataToBlob(src),name=`geofoto-${Date.now()}.jpg`,st=$('#saveStatus');try{const f=new File([blob],name,{type:'image/jpeg'});if(navigator.canShare&&navigator.canShare({files:[f]})&&navigator.share){await navigator.share({title:'Salvar foto',files:[f]});if(st)st.textContent='✓ Foto pronta para salvar/compartilhar no aparelho.';return}saveBlob(blob,name);if(st)st.textContent='✓ Download da foto iniciado.'}catch(e){try{const u=URL.createObjectURL(blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),30000);if(st)st.textContent='Abra a imagem e use Salvar/Download no navegador.'}catch{if(st)st.textContent='Não foi possível salvar a foto neste navegador.'}}}
async function shareCurrent(){return shareBlob(dataToBlob(photo||raw),`geofoto-${Date.now()}.jpg`)}
async function shareRecord(id){const p=points.find(x=>x.id===id);if(!p)return;if(p.photo)return shareBlob(dataToBlob(p.photo),`${safeName(p.name)}.jpg`);if(p.photoUrl){const b=await apiBlob(p.photoUrl);return shareBlob(b,`${safeName(p.name)}.jpg`)}}
async function shareBlob(blob,name){const f=new File([blob],name,{type:'image/jpeg'});if(navigator.canShare&&navigator.canShare({files:[f]})){try{return await navigator.share({title:'GeoFoto KMZ',text:'Registro georreferenciado',files:[f]})}catch{}}saveBlob(blob,name)}
async function openRecordPhoto(id){const p=points.find(x=>x.id===id);if(!p)return;let src=p.photo||'',revoke='';try{if(!src&&p.photoUrl){const b=await apiBlob(p.photoUrl);src=URL.createObjectURL(b);revoke=src}if(!src)return;const box=document.createElement('div');box.className='photo-lightbox';const img=document.createElement('img');img.src=src;img.alt='Foto '+p.name;const meta=document.createElement('div');meta.className='photo-lightbox-meta';meta.innerHTML='<b>'+esc(p.name)+'</b><span>'+esc(fmt(p.time))+' · '+Number(p.lat).toFixed(6)+', '+Number(p.lng).toFixed(6)+'</span>';const close=document.createElement('button');close.className='photo-lightbox-close';close.textContent='×';const done=()=>{box.remove();if(revoke)URL.revokeObjectURL(revoke)};close.onclick=done;box.onclick=e=>{if(e.target===box)done()};box.append(close,img,meta);document.body.appendChild(box)}catch(e){alert('Não foi possível abrir a foto: '+e.message)}}
function renderRecords(){$('#records').innerHTML=`<div class="records-list">${points.slice().reverse().map(p=>`<div class="card record-card"><div class="record-head"><div><b>${esc(p.name)}</b><div class="muted small">${fmt(p.time)} · ${esc(p.city||'')}</div></div><span class="badge">${Math.round(p.accuracy||0)} m</span></div>${(p.photo||p.photoUrl)?`<img class="record-photo" data-photo-id="${p.id}" alt="Foto de ${attr(p.name)}">`:''}<div class="muted small">${esc(p.address||'Sem endereço')}</div><div class="muted small">${Number(p.lat).toFixed(6)}, ${Number(p.lng).toFixed(6)}</div><div class="actions"><button class="btn secondary" data-map="${p.lat},${p.lng}">Abrir Maps</button>${(p.photo||p.photoUrl)?`<button class="btn primary" data-share="${p.id}">Enviar</button>`:''}${role==='admin'?`<button class="btn secondary" data-delete="${p.id}">Excluir</button>`:''}</div></div>`).join('')||'<div class="card">Nenhum registro.</div>'}</div>`;document.querySelectorAll('[data-photo-id]').forEach(async img=>{const p=points.find(x=>x.id===img.dataset.photoId);try{if(p?.photo)img.src=p.photo;else if(p?.photoUrl){const b=await apiBlob(p.photoUrl),u=URL.createObjectURL(b);img.src=u;img.onload=()=>setTimeout(()=>URL.revokeObjectURL(u),30000)}}catch{img.alt='Foto indisponível'}});document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>window.open(`https://www.google.com/maps?q=${b.dataset.map}`,'_blank'));document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareRecord(b.dataset.share));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este registro e a foto?'))return;try{await api('/points/'+b.dataset.delete,{method:'DELETE'});await syncDown();renderDashboard();renderRecords();renderExport();if(map)initMap()}catch(e){alert(e.message)}})}
function initMap(){if(!map){map=L.map('map',{zoomControl:true}).setView([-25.43,-49.27],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);markers=L.layerGroup().addTo(map)}markers.clearLayers();const valid=points.filter(p=>Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)));valid.forEach(p=>L.marker([Number(p.lat),Number(p.lng)]).bindPopup(`<b>${esc(p.name)}</b><br>${fmt(p.time)}<br>${esc(p.city||'')}<br>${Number(p.lat).toFixed(6)}, ${Number(p.lng).toFixed(6)}`).addTo(markers));if(valid.length===1)map.setView([Number(valid[0].lat),Number(valid[0].lng)],17);else if(valid.length>1){const g=L.featureGroup(valid.map(p=>L.marker([Number(p.lat),Number(p.lng)])));map.fitBounds(g.getBounds().pad(.2))}setTimeout(()=>map.invalidateSize(),200)}
function renderExport(){$("#export").innerHTML=`<div class="card"><h3>Central de registros</h3><p class="muted">Cada foto salva automaticamente já cria um Placemark no KML/KMZ.</p><div class="actions"><button class="btn secondary" id="refreshCloud">Atualizar da nuvem</button><button class="btn secondary" id="kml">Baixar KML</button><button class="btn primary" id="kmz">Baixar KMZ completo</button></div><div id="exportStatus" class="muted small"></div></div>`;$("#refreshCloud").onclick=async()=>{await syncDown();renderAll();alert("Pontos atualizados.")};$("#kml").onclick=()=>download("geofoto-kmz.kml",makeKml(),"application/vnd.google-earth.kml+xml");$("#kmz").onclick=async()=>{const btn=$("#kmz"),st=$("#exportStatus");btn.disabled=true;btn.textContent="Gerando KMZ...";if(st)st.textContent="Preparando pontos e fotos...";try{const z=new JSZip();z.file("doc.kml",makeKml());let fotos=0;for(const p of points){try{let b=null;if(p.photo)b=dataToBlob(p.photo);else if(p.photoUrl)b=await apiBlob(p.photoUrl);if(b){z.file("fotos/"+safeName(p.name)+"-"+String(p.id).slice(0,8)+".jpg",b);fotos++}}catch{}}if(st)st.textContent=`Compactando ${points.length} pontos e ${fotos} fotos...`;const blob=await z.generateAsync({type:"blob",compression:"DEFLATE"});saveBlob(blob,"geofoto-kmz.kmz");if(st)st.textContent=`✓ KMZ gerado com ${points.length} pontos e ${fotos} fotos.`}catch(e){if(st)st.textContent="Falha ao gerar KMZ.";alert("Falha ao gerar KMZ: "+e.message)}finally{btn.disabled=false;btn.textContent="Baixar KMZ completo"}}}
function renderSettings(){const enabled=cfg.enabledTemplates||Object.keys(TEMPLATES);$('#settings').innerHTML=`<div class="grid2"><div class="card"><h3>Identidade opcional</h3><label class="field">Nome exibido (técnico/usuário)<input id="companyName" value="${attr(cfg.company||'')}" placeholder="Empresa, equipe ou projeto"></label><label class="field">Cor principal<input id="primaryColor" type="color" value="${attr(cfg.primaryColor||'#0f766e')}"></label><label class="field">Logo / banner (opcional)<input id="bannerFile" type="file" accept="image/*"></label>${cfg.banner?`<img class="banner-preview" src="${cfg.banner}">`:''}<div class="actions"><button class="btn primary" id="saveCfg">Salvar identidade</button><button class="btn secondary" id="clearCfg">Remover logo</button></div></div><div class="card"><h3>Modelos de foto</h3><label class="field">Modelo padrão<select id="defaultTemplate">${Object.entries(TEMPLATES).map(([id,t])=>`<option value="${id}" ${id===cfg.defaultTemplate?'selected':''}>${t.name}</option>`).join('')}</select></label><div class="template-list">${Object.entries(TEMPLATES).map(([id,t])=>`<label class="template-option"><input type="checkbox" data-template="${id}" ${enabled.includes(id)?'checked':''}><span><b>${t.name}</b><small>${t.description}</small></span></label>`).join('')}</div><div class="actions"><button class="btn primary" id="saveTemplates">Salvar modelos</button></div></div><div class="card"><h3>Acesso</h3><p class="muted">A identidade não é fixa: cada instalação pode usar sua própria marca ou trabalhar sem marca.</p><div class="actions"><button class="btn primary" id="refresh">Atualizar</button><button class="btn secondary" id="logout">Sair</button></div></div></div>`;$('#logout').onclick=()=>{sessionStorage.removeItem('gf_token');sessionStorage.removeItem('gf_role');token='';role='user';loginView()};$('#refresh').onclick=async()=>{await syncDown();renderAll()};const persist=async()=>{saveCfg();try{await api('/config',{method:'POST',body:JSON.stringify(cfg)})}catch(e){if(role==='admin')alert(e.message)}};$('#saveCfg').onclick=async()=>{cfg.company=$('#companyName').value.trim();cfg.primaryColor=$('#primaryColor').value;const f=$('#bannerFile').files[0];if(f)cfg.banner=await fileData(f);await persist();alert('Identidade salva.')};$('#clearCfg').onclick=async()=>{cfg.banner='';await persist();renderSettings()};$('#saveTemplates').onclick=async()=>{const ids=[...document.querySelectorAll('[data-template]:checked')].map(x=>x.dataset.template);cfg.enabledTemplates=ids.length?ids:['essential'];cfg.defaultTemplate=cfg.enabledTemplates.includes($('#defaultTemplate').value)?$('#defaultTemplate').value:cfg.enabledTemplates[0];await persist();alert('Modelos atualizados.')}}
function makeKml(){return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>GeoFoto KMZ</name>${points.map(p=>`<Placemark><name>${xml(p.name)}</name><description>${xml(`${p.note||''} | ${fmt(p.time)} | ${p.city||''} | ${p.address||''} | Precisão ${Math.round(p.accuracy||0)}m`)}</description><Point><coordinates>${p.lng},${p.lat},0</coordinates></Point></Placemark>`).join('')}</Document></kml>`}
function fileData(f){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)})}
function dataToBlob(u){const p=u.split(','),m=(p[0].match(/:(.*?);/)||[])[1]||'image/jpeg',b=atob(p[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return new Blob([a],{type:m})}
function download(n,t,type){saveBlob(new Blob([t],{type}),n)}
function saveBlob(b,n){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.rel='noopener';a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(u)},15000)}
function fmt(v){return new Date(v).toLocaleString('pt-BR')}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(s=''){return String(s).replace(/"/g,'&quot;')}
function xml(s=''){return esc(s)}
function safeName(s='registro'){return String(s).replace(/[^a-z0-9_-]+/gi,'-')}



function photoPath(p){return 'fotos/'+safeName(p.name)+'-'+String(p.id).slice(0,8)+'.jpg'}
document.addEventListener('click',e=>{const img=e.target.closest&&e.target.closest('[data-photo-id]');if(img)openRecordPhoto(img.dataset.photoId)});
makeKml=function(withPhotos=false){
 const items=points.map(p=>{const info=(p.note||'')+' | '+fmt(p.time)+' | '+(p.city||'')+' | '+(p.address||'')+' | Precisão '+Math.round(p.accuracy||0)+'m';
  const image=withPhotos&&(p.photo||p.photoUrl)?'<br><img src="'+photoPath(p)+'" width="640">':'';
  return '<Placemark><name>'+xml(p.name)+'</name><description><![CDATA['+esc(info)+image+']]></description><Point><coordinates>'+p.lng+','+p.lat+',0</coordinates></Point></Placemark>'});
 return '<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>GeoFoto KMZ</name>'+items.join('')+'</Document></kml>'
};

renderExport=function(){
 $('#export').innerHTML='<div class="card export-center"><div class="export-badge">KMZ</div><h3>Exportar para Google Earth</h3><p class="muted">O KMZ inclui os pontos, metadados e as fotos vinculadas aos respectivos registros.</p><div class="export-metrics"><div><b>'+points.length+'</b><span>Pontos</span></div><div><b>'+points.filter(p=>p.photo||p.photoUrl).length+'</b><span>Fotos</span></div></div><div class="actions"><button class="btn secondary" id="refreshCloud">Atualizar nuvem</button><button class="btn secondary" id="kml">Baixar KML</button><button class="btn primary" id="kmz">Baixar KMZ completo</button></div><div id="exportStatus" class="muted small"></div></div>';
 $('#refreshCloud').onclick=async()=>{await syncDown();renderAll();alert('Pontos atualizados.')};
 $('#kml').onclick=()=>download('geofoto-kmz.kml',makeKml(false),'application/vnd.google-earth.kml+xml');
 $('#kmz').onclick=async()=>{const btn=$('#kmz'),st=$('#exportStatus');btn.disabled=true;btn.textContent='Gerando KMZ...';if(st)st.textContent='Preparando pontos e fotos...';
  try{const z=new JSZip();z.file('doc.kml',makeKml(true));let fotos=0;
   for(const p of points){try{let b=null;if(p.photo)b=dataToBlob(p.photo);else if(p.photoUrl)b=await apiBlob(p.photoUrl);if(b){z.file(photoPath(p),b);fotos++}}catch{}}
   if(st)st.textContent='Compactando '+points.length+' pontos e '+fotos+' fotos...';
   const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});saveBlob(blob,'geofoto-kmz.kmz');
   if(st)st.textContent='✓ KMZ gerado com '+points.length+' pontos e '+fotos+' fotos vinculadas.'
  }catch(e){if(st)st.textContent='Falha ao gerar KMZ.';alert('Falha ao gerar KMZ: '+e.message)}
  finally{btn.disabled=false;btn.textContent='Baixar KMZ completo'}
 };
};

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));token?appView().catch(loginView):loginView()
